name: CI for meeting2tasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand({ping:1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies for ai-service
      working-directory: ./ai-service
      run: |
        pip install -r requirements.txt

    - name: Debug environment
      run: |
        java --version
        mvn --version
        python --version
        pip --version
        echo "MongoDB container logs:"
        docker logs $(docker ps -q -f ancestor=mongo:4.4)

    - name: Build and Test Task Service
      working-directory: ./task-service
      run: |
        mvn clean install

    - name: Build and Test Scheduling Service
      working-directory: ./scheduling-service
      run: |
        mvn clean install


    - name: Debug OPENAI_API_KEY
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        if [ -z "$OPENAI_API_KEY" ]; then
          echo "OPENAI_API_KEY is not set or empty"
          exit 1
        else
          echo "OPENAI_API_KEY is set (value not shown for security)"
        fi

    - name: Test AI Service
      working-directory: ./ai-service
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        # Chờ server khởi động, thử tối đa 30 giây
        for i in {1..30}; do
          curl --fail http://localhost:8000/docs && break || sleep 1
        done
        # Gửi request thử nghiệm
        curl -X POST http://localhost:8000/extract-tasks \
          -H "Content-Type: application/json" \
          -d '{"user_input": "Test task generation", "project_id": null}' || exit 1