name: CI for meeting2tasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --host localhost --port 27017 --eval 'db.adminCommand({ping:1})'"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 15

    steps:
    - uses: actions/checkout@v3

    - name: Debug MongoDB container
      run: |
        echo "MongoDB container logs:"
        docker logs $(docker ps -q -f ancestor=mongo:6.0) || echo "No MongoDB container logs available"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and Test Task Service
      working-directory: ./task-service
      run: |
        mvn clean install

    - name: Build and Test Scheduling Service
      working-directory: ./scheduling-service
      run: |
        mvn clean install

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build and Test AI Model
      working-directory: ./ai-model
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Thêm test nếu cần (ví dụ: pytest)