name: CI for meeting2tasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --host localhost --port 27017 --eval 'db.adminCommand({ping:1})'"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 15
      zookeeper:
        image: bitnami/zookeeper:3.8
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ALLOW_ANONYMOUS_LOGIN: yes
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_INIT_LIMIT: 15
          ZOOKEEPER_SYNC_LIMIT: 5
        ports:
          - 2181:2181
        volumes:
          - zookeeper_data:/bitnami/zookeeper
        options: >-
          --health-cmd "sh -c 'netstat -an | grep 2181 || exit 1'"
          --health-interval 10s
          --health-timeout 15s
          --health-retries 30
      kafka:
        image: confluentinc/cp-kafka:7.3.0
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "kafka-topics --list --bootstrap-server kafka:9092"
          --health-interval 10s
          --health-timeout 15s
          --health-retries 30

    steps:
    - uses: actions/checkout@v3

    - name: Debug Zookeeper container
      run: |
        echo "Zookeeper container logs:"
        docker ps -a
        docker logs $(docker ps -q -f ancestor=bitnami/zookeeper:3.8) || echo "No Zookeeper container logs available"
        echo "Checking if port 2181 is listening:"
        docker exec $(docker ps -q -f ancestor=bitnami/zookeeper:3.8) netstat -an | grep 2181 || echo "Port 2181 not listening"

    - name: Debug MongoDB container
      run: |
        echo "MongoDB container logs:"
        docker logs $(docker ps -q -f ancestor=mongo:6.0) || echo "No MongoDB container logs available"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Wait for Kafka to be ready
      run: |
        echo "Waiting for Kafka to be ready..."
        for i in {1..30}; do
          if kafka-topics --list --bootstrap-server kafka:9092; then
            echo "Kafka is ready!"
            break
          fi
          echo "Kafka not ready yet, retrying ($i/30)..."
          sleep 5
        done

    - name: Debug environment
      run: |
        java --version
        mvn --version
        echo "MongoDB container logs:"
        docker logs $(docker ps -q -f ancestor=mongo:6.0)
        echo "Kafka container logs:"
        docker logs $(docker ps -q -f ancestor=confluentinc/cp-kafka:7.3.0)

    - name: Build and Test Task Service
      working-directory: ./task-service
      run: |
        mvn clean install

    - name: Build and Test Scheduling Service
      working-directory: ./scheduling-service
      run: |
        mvn clean install

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build and Test AI Model
      working-directory: ./ai-model
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Thêm test nếu cần (ví dụ: pytest)