name: CI for meeting2task

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-task-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Task Service
      working-directory: ./task-service
      run: mvn clean install

  build-scheduling-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Scheduling Service
      working-directory: ./scheduling-service
      run: mvn clean install

  build-assignment-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Assignment Service
      working-directory: ./assignment-service
      run: mvn clean install

  build-learning-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      working-directory: ./learning-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      working-directory: ./frontend
      run: npm install
    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build